defaultNamespace: demoapp
name: demoapp-dependencies
targetCustomizations:
- name: lab
  yaml:
    overlays:
      - lab
  clusterSelector:
    matchLabels:
      environment: spr-lab
      demoapp: true