global:
  imagePullSecrets: []

# Todo: set it as preexisting secret  
existingSecretAdminPassword: "suse-private-registry-admin-creds"
existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD


expose:
  type: loadBalancer
  # loadBalancer:
  #   IP: "192.168.0.152"
  tls:
    certSource: secret
    secret:
      secretName: "tls-suse-private-registry"

externalURL: "https://suse-registry.marth52creative.xyz"

metrics:
  enabled: false

containerSecurityContext:
  privileged: false
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

nginx:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 100m 
portal:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 100m 

core:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
  configureUserSettings: |
    {
      "auth_mode": "oidc_auth",
      "oidc_name": "Rancher",
      "oidc_endpoint": "rancher-prime.marth52creative.xyz/oidc",
      "oidc_client_id": "client-5h994nl8dc",
      "oidc_client_secret": "secret-q58ljkv4kdz74b5ngp4gjfvd88pqtgz28zp6wrsf9tzjfkfn5xxbhlw4",
      "oidc_scope": "openid,profile,offline_access",
      "oidc_verify_cert": true,
      "oidc_auto_onboard": true,
      "oidc_user_claim": "preferred_username",
      "oidc_groups_claim": "groups",
      "oidc_admin_group": "spr-admins"
    }
    
jobservice:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m    

registry:
  registry:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
  controller:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m    

redis:
  type: internal
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m  

database:
  # if external database is used, set "type" to "external"
  # and fill the connection information in "external" section
  type: internal
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

trivy:
  enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m  

exporter:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m    