server {
        listen 8443 ssl;
        server_name {{ .Values.service.loadBalancer.host }};

        # Paths where the secret will be mounted
        ssl_certificate     /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }