# Default values for demoapp.
replicaCount: 3

imagePullSecrets:
  - name: private-registry-imagepull

global:
  cattle:
    environment: "Lab Environment"
    # Set by Fleet templating in fleet.yaml.
    clusterName: ${ if hasKey .ClusterLabels "management.cattle.io/cluster-display-name" }${ get .ClusterLabels "management.cattle.io/cluster-display-name" }${ else }unknown-cluster${ end }
    url: https://rancher-prime.marth52creative.xyz/

ingress:
  enabled: true
  className: "traefik"
  hosts:
      # fleet template function to set the hostname based on the cluster name label, with a fallback for unknown clusters
    #- host: ${ if hasKey .ClusterLabels "management.cattle.io/cluster-display-name" }${ get .ClusterLabels "management.cattle.io/cluster-display-name" }${ else }unknown-cluster${ end }-demo-app.zeiss.org
    - host: demoapp.marth52creative.xyz  
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: "tls-demo-app"
      hosts:
        - demoapp-landingpage.marth52creative.xyz
        #- ${ if hasKey .ClusterLabels "management.cattle.io/cluster-display-name" }${ get .ClusterLabels "management.cattle.io/cluster-display-name" }${ else }unknown-cluster${ end }-demo-app.zeiss.org