apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-demo-app
  namespace: demoapp
spec:
  secretName: tls-demo-app
  commonName: demoapp.marth52creative.xyz
  dnsNames:
  - demoapp.marth52creative.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer